insert into ipsums(id,name,uri,adminKey,adminEmail) values(562,'Jean Jacques','jjg','B0efkloo','jj@goldman.com');
insert into ipsumtext(ipsum_id,data) values(562,'A tous mes loupés, mes ratés, mes vrais soleils');
insert into ipsumtext(ipsum_id,data) values(562,'Tous les chemins qui me sont passés à  côté');
insert into ipsumtext(ipsum_id,data) values(562,'A tous mes bateaux manqués, mes mauvais sommeils');
insert into ipsumtext(ipsum_id,data) values(562,'A tous ceux que je n ai pas été');
insert into ipsumtext(ipsum_id,data) values(562,'Aux malentendus, aux mensonges, à  nos silences');
insert into ipsumtext(ipsum_id,data) values(562, "A tous ces moments que j'avais cru partager");
insert into ipsumtext(ipsum_id,data) values(562, "Aux phrases qu'on dit trop vite et sans qu'on les pense");
insert into ipsumtext(ipsum_id,data) values(562, "A celles que je n'ai pas osées ");
insert into ipsumtext(ipsum_id,data) values(562, "A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "Aux années perdues à  tenter de ressembler");
insert into ipsumtext(ipsum_id,data) values(562, "A tous les murs que je n'aurais pas su briser");
insert into ipsumtext(ipsum_id,data) values(562, "A tout c'que j'ai pas vu tout près, juste à côté");
insert into ipsumtext(ipsum_id,data) values(562, "Tout c'que j'aurais mieux fait d'ignorer");
insert into ipsumtext(ipsum_id,data) values(562, "Au monde, à  ses douleurs qui ne me touchent plus");
insert into ipsumtext(ipsum_id,data) values(562, "Aux notes, aux solos que je n'ai pas inventés");
insert into ipsumtext(ipsum_id,data) values(562, "Tous ces mots que d'autres ont fait rimer et qui me tuent");
insert into ipsumtext(ipsum_id,data) values(562, "Comme autant d'enfants jamais portés ");
insert into ipsumtext(ipsum_id,data) values(562, "A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "Aux amours échouées de s'être trop aimé");
insert into ipsumtext(ipsum_id,data) values(562, "Visages et dentelles croisés justes frôlés");
insert into ipsumtext(ipsum_id,data) values(562, "Aux trahisons que j'ai pas vraiment regrettées");
insert into ipsumtext(ipsum_id,data) values(562, "Aux vivants qu'il aurait fallu tuer");
insert into ipsumtext(ipsum_id,data) values(562, "A tout ce qui nous arrive enfin, mais trop tard");
insert into ipsumtext(ipsum_id,data) values(562, "A tous les masques qu'il aura fallu porter");

insert into ipsumtext(ipsum_id,data) values(562, "aa A tous mes loupés, mes ratés, mes vrais soleils");
insert into ipsumtext(ipsum_id,data) values(562, "aa Tous les chemins qui me sont passés à  côté");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tous mes bateaux manqués, mes mauvais sommeils");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tous ceux que je n ai pas été");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux malentendus, aux mensonges, à  nos silences");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tous ces moments que j'avais cru partager");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux phrases qu'on dit trop vite et sans qu'on les pense");
insert into ipsumtext(ipsum_id,data) values(562, "aa A celles que je n'ai pas osées ");
insert into ipsumtext(ipsum_id,data) values(562, "aa A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux années perdues à  tenter de ressembler");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tous les murs que je n'aurais pas su briser");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tout c'que j'ai pas vu tout près, juste à côté");
insert into ipsumtext(ipsum_id,data) values(562, "aa Tout c'que j'aurais mieux fait d'ignorer");
insert into ipsumtext(ipsum_id,data) values(562, "aa Au monde, à  ses douleurs qui ne me touchent plus");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux notes, aux solos que je n'ai pas inventés");
insert into ipsumtext(ipsum_id,data) values(562, "aa Tous ces mots que d'autres ont fait rimer et qui me tuent");
insert into ipsumtext(ipsum_id,data) values(562, "aa Comme autant d'enfants jamais portés ");
insert into ipsumtext(ipsum_id,data) values(562, "aa A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux amours échouées de s'être trop aimé");
insert into ipsumtext(ipsum_id,data) values(562, "aa Visages et dentelles croisés justes frôlés");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux trahisons que j'ai pas vraiment regrettées");
insert into ipsumtext(ipsum_id,data) values(562, "aa Aux vivants qu'il aurait fallu tuer");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tout ce qui nous arrive enfin, mais trop tard");
insert into ipsumtext(ipsum_id,data) values(562, "aa A tous les masques qu'il aura fallu porter");

insert into ipsumtext(ipsum_id,data) values(562, "bb A tous mes loupés, mes ratés, mes vrais soleils");
insert into ipsumtext(ipsum_id,data) values(562, "bb Tous les chemins qui me sont passés à  côté");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tous mes bateaux manqués, mes mauvais sommeils");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tous ceux que je n ai pas été");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux malentendus, aux mensonges, à  nos silences");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tous ces moments que j'avais cru partager");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux phrases qu'on dit trop vite et sans qu'on les pense");
insert into ipsumtext(ipsum_id,data) values(562, "bb A celles que je n'ai pas osées ");
insert into ipsumtext(ipsum_id,data) values(562, "bb A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux années perdues à  tenter de ressembler");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tous les murs que je n'aurais pas su briser");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tout c'que j'ai pas vu tout près, juste à côté");
insert into ipsumtext(ipsum_id,data) values(562, "bb Tout c'que j'aurais mieux fait d'ignorer");
insert into ipsumtext(ipsum_id,data) values(562, "bb Au monde, à  ses douleurs qui ne me touchent plus");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux notes, aux solos que je n'ai pas inventés");
insert into ipsumtext(ipsum_id,data) values(562, "bb Tous ces mots que d'autres ont fait rimer et qui me tuent");
insert into ipsumtext(ipsum_id,data) values(562, "bb Comme autant d'enfants jamais portés ");
insert into ipsumtext(ipsum_id,data) values(562, "bb A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux amours échouées de s'être trop aimé");
insert into ipsumtext(ipsum_id,data) values(562, "bb Visages et dentelles croisés justes frôlés");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux trahisons que j'ai pas vraiment regrettées");
insert into ipsumtext(ipsum_id,data) values(562, "bb Aux vivants qu'il aurait fallu tuer");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tout ce qui nous arrive enfin, mais trop tard");
insert into ipsumtext(ipsum_id,data) values(562, "bb A tous les masques qu'il aura fallu porter");

insert into ipsumtext(ipsum_id,data) values(562, "cc A tous mes loupés, mes ratés, mes vrais soleils");
insert into ipsumtext(ipsum_id,data) values(562, "cc Tous les chemins qui me sont passés à  côté");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tous mes bateaux manqués, mes mauvais sommeils");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tous ceux que je n ai pas été");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux malentendus, aux mensonges, à  nos silences");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tous ces moments que j'avais cru partager");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux phrases qu'on dit trop vite et sans qu'on les pense");
insert into ipsumtext(ipsum_id,data) values(562, "cc A celles que je n'ai pas osées ");
insert into ipsumtext(ipsum_id,data) values(562, "cc A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux années perdues à  tenter de ressembler");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tous les murs que je n'aurais pas su briser");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tout c'que j'ai pas vu tout près, juste à côté");
insert into ipsumtext(ipsum_id,data) values(562, "cc Tout c'que j'aurais mieux fait d'ignorer");
insert into ipsumtext(ipsum_id,data) values(562, "cc Au monde, à  ses douleurs qui ne me touchent plus");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux notes, aux solos que je n'ai pas inventés");
insert into ipsumtext(ipsum_id,data) values(562, "cc Tous ces mots que d'autres ont fait rimer et qui me tuent");
insert into ipsumtext(ipsum_id,data) values(562, "cc Comme autant d'enfants jamais portés ");
insert into ipsumtext(ipsum_id,data) values(562, "cc A nos actes manqués");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux amours échouées de s'être trop aimé");
insert into ipsumtext(ipsum_id,data) values(562, "cc Visages et dentelles croisés justes frôlés");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux trahisons que j'ai pas vraiment regrettées");
insert into ipsumtext(ipsum_id,data) values(562, "cc Aux vivants qu'il aurait fallu tuer");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tout ce qui nous arrive enfin, mais trop tard");
insert into ipsumtext(ipsum_id,data) values(562, "cc A tous les masques qu'il aura fallu porter");
